/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Seafoam (https://sketchfab.com/seafoam)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/smol-holomyth-halloween-costumes-1e2305d63e084c1e966630496b6deb5b
title: Smol HoloMyth Halloween Costumes!
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Object_76: THREE.SkinnedMesh;
    Object_77: THREE.SkinnedMesh;
    Object_152: THREE.SkinnedMesh;
    Object_153: THREE.SkinnedMesh;
    Object_154: THREE.SkinnedMesh;
    Object_236: THREE.SkinnedMesh;
    Object_237: THREE.SkinnedMesh;
    Object_317: THREE.SkinnedMesh;
    Object_318: THREE.SkinnedMesh;
    Object_394: THREE.SkinnedMesh;
    Object_395: THREE.SkinnedMesh;
    Kiara_parasol_HW_smolkiara_0: THREE.Mesh;
    _rootJoint: THREE.Bone;
    _rootJoint_1: THREE.Bone;
    _rootJoint_2: THREE.Bone;
    _rootJoint_3: THREE.Bone;
    _rootJoint_4: THREE.Bone;
  };
  materials: {
    outline: THREE.MeshStandardMaterial;
    Hw_smolametex: THREE.MeshStandardMaterial;
    HWSmolCalli: THREE.MeshStandardMaterial;
    SmolCalliVeil: THREE.MeshStandardMaterial;
    SmolGura: THREE.MeshStandardMaterial;
    HW_SmolIna: THREE.MeshStandardMaterial;
    HW_smolkiara: THREE.MeshStandardMaterial;
  };
};

type ModelProps = {
  shadows?: boolean;
} & JSX.IntrinsicElements['group'];

export default function Model({ shadows = false, ...props }: ModelProps) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/hololive.glb') as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.39}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh
              geometry={nodes.Object_76.geometry}
              material={materials.outline}
              skeleton={nodes.Object_76.skeleton}
            />
            <skinnedMesh
              castShadow={shadows}
              geometry={nodes.Object_77.geometry}
              material={materials.Hw_smolametex}
              skeleton={nodes.Object_77.skeleton}
            />
          </group>
          <group
            position={[-490.6, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0.46]}
            scale={100}
          >
            <primitive object={nodes._rootJoint_1} />
            <skinnedMesh
              castShadow={shadows}
              geometry={nodes.Object_152.geometry}
              material={materials.HWSmolCalli}
              skeleton={nodes.Object_152.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_153.geometry}
              material={materials.outline}
              skeleton={nodes.Object_153.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_154.geometry}
              material={materials.SmolCalliVeil}
              skeleton={nodes.Object_154.skeleton}
            />
          </group>
          <group
            position={[440.42, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes._rootJoint_2} />
            <skinnedMesh
              castShadow={shadows}
              geometry={nodes.Object_236.geometry}
              material={materials.SmolGura}
              skeleton={nodes.Object_236.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_237.geometry}
              material={materials.outline}
              skeleton={nodes.Object_237.skeleton}
            />
          </group>
          <group
            position={[227.99, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes._rootJoint_3} />
            <skinnedMesh
              castShadow={shadows}
              geometry={nodes.Object_317.geometry}
              material={materials.HW_SmolIna}
              skeleton={nodes.Object_317.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_318.geometry}
              material={materials.outline}
              skeleton={nodes.Object_318.skeleton}
            />
          </group>
          <group
            position={[-245.13, 0, 0]}
            rotation={[-Math.PI / 2, 0, 0.18]}
            scale={100}
          >
            <primitive object={nodes._rootJoint_4} />
            <skinnedMesh
              castShadow={shadows}
              geometry={nodes.Object_394.geometry}
              material={materials.HW_smolkiara}
              skeleton={nodes.Object_394.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_395.geometry}
              material={materials.outline}
              skeleton={nodes.Object_395.skeleton}
            />
          </group>
          <group
            position={[-217.03, 87.62, 52.92]}
            rotation={[-2.32, -0.57, -0.62]}
            scale={[110.45, 110.46, 118.51]}
          >
            <mesh
              castShadow={shadows}
              geometry={nodes.Kiara_parasol_HW_smolkiara_0.geometry}
              material={materials.HW_smolkiara}
            />
          </group>
        </group>
      </group>
    </group>
  );
}
